apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crypto-insight-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - crypto-insight
  selector:
    matchLabels:
      app: crypto-insight
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s