apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-insight
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vxtsxl/crypto-insight.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-insight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true