apiVersion: v1
kind: Service
metadata:
  name: crypto-insight-service
  namespace: crypto-insight
  labels:
    app: crypto-insight
spec:
  type: ClusterIP
  selector:
    app: crypto-insight
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP